# Uncomment this line to define a global platform for your project
platform :osx, '10.10'
use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.5.0'
    pod 'Nimble', '2.0.0-rc.2'
end

target 'Harbor' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
end

target 'HarborTests' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
    testing_pods
end

target 'HarborUITests' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
    testing_pods
end

